### ISSUE TITLE
Error while running terraform init

### ISSUE THREAD

**Issue by uu5jor** [hashicorp/learn-terraform-plan#10]
Hi!
I'm following the documentation https://developer.hashicorp.com/terraform/tutorials/cli/plan 
but on the stage when I run terraform init I'm getting:

│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider kreuzwerker/docker: locked provider
│ registry.terraform.io/kreuzwerker/docker 2.16.0 does not match configured version constraint ~> 2.16.0, ~> 2.22.0;
│ must use terraform init -upgrade to allow selection of new versions

Tried to run terraform init -upgrade but it loops on the same:

 Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider kreuzwerker/docker: no available releases match the
│ given constraints ~> 2.16.0, ~> 2.22.0

Please suggest what is missing here.
Thanks in advance!

Iryna

**Comment by judithpatudith** [comment]
Hi! I was able to reproduce this. Removing the version constraint and running `terraform init -upgrade` fixes it for now, but I'm still trying to figure out what's going wrong with the version constraint 🤔 

Thank you for the report!

**Comment by robin-norwood** [comment]
Fixed by #11
